INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('PIDIE JAYA',1),
	 ('SIMEULUE',1),
	 ('BIREUEN',1),
	 ('ACEH TIMUR',1),
	 ('ACEH UTARA',1),
	 ('PIDIE',1),
	 ('ACEH BARAT DAYA',1),
	 ('GAYO LUES',1),
	 ('ACEH SELATAN',1),
	 ('ACEH TAMIANG',1);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('ACEH BESAR',1),
	 ('ACEH TENGGARA',1),
	 ('BENER MERIAH',1),
	 ('ACEH JAYA',1),
	 ('LHOKSEUMAWE',1),
	 ('ACEH BARAT',1),
	 ('NAGAN RAYA',1),
	 ('LANGSA',1),
	 ('BANDA ACEH',1),
	 ('ACEH SINGKIL',1);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('SABANG',1),
	 ('ACEH TENGAH',1),
	 ('SUBULUSSALAM',1),
	 ('NIAS SELATAN',2),
	 ('MANDAILING NATAL',2),
	 ('DAIRI',2),
	 ('LABUHAN BATU UTARA',2),
	 ('TAPANULI UTARA',2),
	 ('SIMALUNGUN',2),
	 ('LANGKAT',2);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('SERDANG BEDAGAI',2),
	 ('TAPANULI SELATAN',2),
	 ('ASAHAN',2),
	 ('PADANG LAWAS UTARA',2),
	 ('PADANG LAWAS',2),
	 ('LABUHAN BATU SELATAN',2),
	 ('PADANG SIDEMPUAN',2),
	 ('TOBA SAMOSIR',2),
	 ('TAPANULI TENGAH',2),
	 ('HUMBANG HASUNDUTAN',2);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('SIBOLGA',2),
	 ('BATU BARA',2),
	 ('SAMOSIR',2),
	 ('PEMATANG SIANTAR',2),
	 ('LABUHAN BATU',2),
	 ('DELI SERDANG',2),
	 ('GUNUNGSITOLI',2),
	 ('NIAS UTARA',2),
	 ('NIAS',2),
	 ('KARO',2);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('NIAS BARAT',2),
	 ('MEDAN',2),
	 ('PAKPAK BHARAT',2),
	 ('TEBING TINGGI',2),
	 ('BINJAI',2),
	 ('TANJUNG BALAI',2),
	 ('DHARMASRAYA',3),
	 ('SOLOK SELATAN',3),
	 ('SIJUNJUNG (SAWAH LUNTO SIJUNJUNG)',3),
	 ('PASAMAN BARAT',3);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('SOLOK',3),
	 ('PASAMAN',3),
	 ('PARIAMAN',3),
	 ('TANAH DATAR',3),
	 ('PADANG PARIAMAN',3),
	 ('PESISIR SELATAN',3),
	 ('PADANG',3),
	 ('SAWAH LUNTO',3),
	 ('LIMA PULUH KOTO / KOTA',3),
	 ('AGAM',3);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('PAYAKUMBUH',3),
	 ('BUKITTINGGI',3),
	 ('PADANG PANJANG',3),
	 ('KEPULAUAN MENTAWAI',3),
	 ('INDRAGIRI HILIR',4),
	 ('KUANTAN SINGINGI',4),
	 ('PELALAWAN',4),
	 ('PEKANBARU',4),
	 ('ROKAN HILIR',4),
	 ('BENGKALIS',4);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('INDRAGIRI HULU',4),
	 ('ROKAN HULU',4),
	 ('KAMPAR',4),
	 ('KEPULAUAN MERANTI',4),
	 ('DUMAI',4),
	 ('SIAK',4),
	 ('TEBO',5),
	 ('TANJUNG JABUNG BARAT',5),
	 ('MUARO JAMBI',5),
	 ('KERINCI',5);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('MERANGIN',5),
	 ('BUNGO',5),
	 ('TANJUNG JABUNG TIMUR',5),
	 ('SUNGAIPENUH',5),
	 ('BATANG HARI',5),
	 ('JAMBI',5),
	 ('SAROLANGUN',5),
	 ('PALEMBANG',6),
	 ('LAHAT',6),
	 ('OGAN KOMERING ULU TIMUR',6);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('MUSI BANYUASIN',6),
	 ('PAGAR ALAM',6),
	 ('OGAN KOMERING ULU SELATAN',6),
	 ('BANYUASIN',6),
	 ('MUSI RAWAS',6),
	 ('MUARA ENIM',6),
	 ('OGAN KOMERING ULU',6),
	 ('OGAN KOMERING ILIR',6),
	 ('EMPAT LAWANG',6),
	 ('LUBUK LINGGAU',6);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('PRABUMULIH',6),
	 ('OGAN ILIR',6),
	 ('BENGKULU TENGAH',7),
	 ('REJANG LEBONG',7),
	 ('MUKO MUKO',7),
	 ('KAUR',7),
	 ('BENGKULU UTARA',7),
	 ('LEBONG',7),
	 ('KEPAHIANG',7),
	 ('BENGKULU SELATAN',7);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('SELUMA',7),
	 ('BENGKULU',7),
	 ('LAMPUNG UTARA',8),
	 ('WAY KANAN',8),
	 ('LAMPUNG TENGAH',8),
	 ('MESUJI',8),
	 ('PRINGSEWU',8),
	 ('LAMPUNG TIMUR',8),
	 ('LAMPUNG SELATAN',8),
	 ('TULANG BAWANG',8);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('TULANG BAWANG BARAT',8),
	 ('TANGGAMUS',8),
	 ('LAMPUNG BARAT',8),
	 ('PESISIR BARAT',8),
	 ('PESAWARAN',8),
	 ('BANDAR LAMPUNG',8),
	 ('METRO',8),
	 ('BELITUNG',9),
	 ('BELITUNG TIMUR',9),
	 ('BANGKA',9);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('BANGKA SELATAN',9),
	 ('BANGKA BARAT',9),
	 ('PANGKAL PINANG',9),
	 ('BANGKA TENGAH',9),
	 ('KEPULAUAN ANAMBAS',10),
	 ('BINTAN',10),
	 ('NATUNA',10),
	 ('BATAM',10),
	 ('TANJUNG PINANG',10),
	 ('KARIMUN',10);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('LINGGA',10),
	 ('JAKARTA UTARA',11),
	 ('JAKARTA BARAT',11),
	 ('JAKARTA TIMUR',11),
	 ('JAKARTA SELATAN',11),
	 ('JAKARTA PUSAT',11),
	 ('KEPULAUAN SERIBU',11),
	 ('DEPOK',12),
	 ('KARAWANG',12),
	 ('CIREBON',12);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('BANDUNG',12),
	 ('SUKABUMI',12),
	 ('SUMEDANG',12),
	 ('INDRAMAYU',12),
	 ('MAJALENGKA',12),
	 ('KUNINGAN',12),
	 ('TASIKMALAYA',12),
	 ('CIAMIS',12),
	 ('SUBANG',12),
	 ('PURWAKARTA',12);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('BOGOR',12),
	 ('BEKASI',12),
	 ('GARUT',12),
	 ('PANGANDARAN',12),
	 ('CIANJUR',12),
	 ('BANJAR',12),
	 ('BANDUNG BARAT',12),
	 ('CIMAHI',12),
	 ('PURBALINGGA',13),
	 ('KEBUMEN',13);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('MAGELANG',13),
	 ('CILACAP',13),
	 ('BATANG',13),
	 ('BANJARNEGARA',13),
	 ('BLORA',13),
	 ('BREBES',13),
	 ('BANYUMAS',13),
	 ('WONOSOBO',13),
	 ('TEGAL',13),
	 ('PURWOREJO',13);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('PATI',13),
	 ('SUKOHARJO',13),
	 ('KARANGANYAR',13),
	 ('PEKALONGAN',13),
	 ('PEMALANG',13),
	 ('BOYOLALI',13),
	 ('GROBOGAN',13),
	 ('SEMARANG',13),
	 ('DEMAK',13),
	 ('REMBANG',13);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('KLATEN',13),
	 ('KUDUS',13),
	 ('TEMANGGUNG',13),
	 ('SRAGEN',13),
	 ('JEPARA',13),
	 ('WONOGIRI',13),
	 ('KENDAL',13),
	 ('SURAKARTA (SOLO)',13),
	 ('SALATIGA',13),
	 ('SLEMAN',14);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('BANTUL',14),
	 ('YOGYAKARTA',14),
	 ('GUNUNG KIDUL',14),
	 ('KULON PROGO',14),
	 ('GRESIK',15),
	 ('KEDIRI',15),
	 ('SAMPANG',15),
	 ('BANGKALAN',15),
	 ('SUMENEP',15),
	 ('SITUBONDO',15);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('SURABAYA',15),
	 ('JEMBER',15),
	 ('PAMEKASAN',15),
	 ('JOMBANG',15),
	 ('PROBOLINGGO',15),
	 ('BANYUWANGI',15),
	 ('PASURUAN',15),
	 ('BOJONEGORO',15),
	 ('BONDOWOSO',15),
	 ('MAGETAN',15);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('LUMAJANG',15),
	 ('MALANG',15),
	 ('BLITAR',15),
	 ('SIDOARJO',15),
	 ('LAMONGAN',15),
	 ('PACITAN',15),
	 ('TULUNGAGUNG',15),
	 ('MOJOKERTO',15),
	 ('MADIUN',15),
	 ('PONOROGO',15);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('NGAWI',15),
	 ('NGANJUK',15),
	 ('TUBAN',15),
	 ('TRENGGALEK',15),
	 ('BATU',15),
	 ('TANGERANG',16),
	 ('SERANG',16),
	 ('PANDEGLANG',16),
	 ('LEBAK',16),
	 ('TANGERANG SELATAN',16);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('CILEGON',16),
	 ('KLUNGKUNG',17),
	 ('KARANGASEM',17),
	 ('BANGLI',17),
	 ('TABANAN',17),
	 ('GIANYAR',17),
	 ('BADUNG',17),
	 ('JEMBRANA',17),
	 ('BULELENG',17),
	 ('DENPASAR',17);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('MATARAM',18),
	 ('DOMPU',18),
	 ('SUMBAWA BARAT',18),
	 ('SUMBAWA',18),
	 ('LOMBOK TENGAH',18),
	 ('LOMBOK TIMUR',18),
	 ('LOMBOK UTARA',18),
	 ('LOMBOK BARAT',18),
	 ('BIMA',18),
	 ('TIMOR TENGAH SELATAN',19);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('FLORES TIMUR',19),
	 ('ALOR',19),
	 ('ENDE',19),
	 ('NAGEKEO',19),
	 ('KUPANG',19),
	 ('SIKKA',19),
	 ('NGADA',19),
	 ('TIMOR TENGAH UTARA',19),
	 ('BELU',19),
	 ('LEMBATA',19);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('SUMBA BARAT DAYA',19),
	 ('SUMBA BARAT',19),
	 ('SUMBA TENGAH',19),
	 ('SUMBA TIMUR',19),
	 ('ROTE NDAO',19),
	 ('MANGGARAI TIMUR',19),
	 ('MANGGARAI',19),
	 ('SABU RAIJUA',19),
	 ('MANGGARAI BARAT',19),
	 ('LANDAK',20);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('KETAPANG',20),
	 ('SINTANG',20),
	 ('KUBU RAYA',20),
	 ('PONTIANAK',20),
	 ('KAYONG UTARA',20),
	 ('BENGKAYANG',20),
	 ('KAPUAS HULU',20),
	 ('SAMBAS',20),
	 ('SINGKAWANG',20),
	 ('SANGGAU',20);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('MELAWI',20),
	 ('SEKADAU',20),
	 ('KOTAWARINGIN TIMUR',21),
	 ('SUKAMARA',21),
	 ('KOTAWARINGIN BARAT',21),
	 ('BARITO TIMUR',21),
	 ('KAPUAS',21),
	 ('PULANG PISAU',21),
	 ('LAMANDAU',21),
	 ('SERUYAN',21);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('KATINGAN',21),
	 ('BARITO SELATAN',21),
	 ('MURUNG RAYA',21),
	 ('BARITO UTARA',21),
	 ('GUNUNG MAS',21),
	 ('PALANGKA RAYA',21),
	 ('TAPIN',22),
	 ('BANJAR',22),
	 ('HULU SUNGAI TENGAH',22),
	 ('TABALONG',22);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('HULU SUNGAI UTARA',22),
	 ('BALANGAN',22),
	 ('TANAH BUMBU',22),
	 ('BANJARMASIN',22),
	 ('KOTABARU',22),
	 ('TANAH LAUT',22),
	 ('HULU SUNGAI SELATAN',22),
	 ('BARITO KUALA',22),
	 ('BANJARBARU',22),
	 ('KUTAI BARAT',23);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('SAMARINDA',23),
	 ('PASER',23),
	 ('KUTAI KARTANEGARA',23),
	 ('BERAU',23),
	 ('PENAJAM PASER UTARA',23),
	 ('BONTANG',23),
	 ('KUTAI TIMUR',23),
	 ('BALIKPAPAN',23),
	 ('MALINAU',24),
	 ('NUNUKAN',24);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('BULUNGAN (BULONGAN)',24),
	 ('TANA TIDUNG',24),
	 ('TARAKAN',24),
	 ('BOLAANG MONGONDOW (BOLMONG)',25),
	 ('BOLAANG MONGONDOW SELATAN',25),
	 ('MINAHASA SELATAN',25),
	 ('BITUNG',25),
	 ('MINAHASA',25),
	 ('KEPULAUAN SANGIHE',25),
	 ('MINAHASA UTARA',25);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('KEPULAUAN TALAUD',25),
	 ('KEPULAUAN SIAU TAGULANDANG BIARO (SITARO)',25),
	 ('MANADO',25),
	 ('BOLAANG MONGONDOW UTARA',25),
	 ('BOLAANG MONGONDOW TIMUR',25),
	 ('MINAHASA TENGGARA',25),
	 ('KOTAMOBAGU',25),
	 ('TOMOHON',25),
	 ('BANGGAI KEPULAUAN',26),
	 ('TOLI-TOLI',26);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('PARIGI MOUTONG',26),
	 ('BUOL',26),
	 ('DONGGALA',26),
	 ('POSO',26),
	 ('MOROWALI',26),
	 ('TOJO UNA-UNA',26),
	 ('BANGGAI',26),
	 ('SIGI',26),
	 ('PALU',26),
	 ('MAROS',27);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('WAJO',27),
	 ('BONE',27),
	 ('SOPPENG',27),
	 ('SIDENRENG RAPPANG / RAPANG',27),
	 ('TAKALAR',27),
	 ('BARRU',27),
	 ('LUWU TIMUR',27),
	 ('SINJAI',27),
	 ('PANGKAJENE KEPULAUAN',27),
	 ('PINRANG',27);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('JENEPONTO',27),
	 ('PALOPO',27),
	 ('TORAJA UTARA',27),
	 ('LUWU',27),
	 ('BULUKUMBA',27),
	 ('MAKASSAR',27),
	 ('SELAYAR (KEPULAUAN SELAYAR)',27),
	 ('TANA TORAJA',27),
	 ('LUWU UTARA',27),
	 ('BANTAENG',27);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('GOWA',27),
	 ('ENREKANG',27),
	 ('PAREPARE',27),
	 ('KOLAKA',28),
	 ('MUNA',28),
	 ('KONAWE SELATAN',28),
	 ('KENDARI',28),
	 ('KONAWE',28),
	 ('KONAWE UTARA',28),
	 ('KOLAKA UTARA',28);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('BUTON',28),
	 ('BOMBANA',28),
	 ('WAKATOBI',28),
	 ('BAU-BAU',28),
	 ('BUTON UTARA',28),
	 ('GORONTALO UTARA',29),
	 ('BONE BOLANGO',29),
	 ('GORONTALO',29),
	 ('BOALEMO',29),
	 ('POHUWATO',29);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('MAJENE',30),
	 ('MAMUJU',30),
	 ('MAMUJU UTARA',30),
	 ('POLEWALI MANDAR',30),
	 ('MAMASA',30),
	 ('MALUKU TENGGARA BARAT',31),
	 ('MALUKU TENGGARA',31),
	 ('SERAM BAGIAN BARAT',31),
	 ('MALUKU TENGAH',31),
	 ('SERAM BAGIAN TIMUR',31);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('MALUKU BARAT DAYA',31),
	 ('AMBON',31),
	 ('BURU',31),
	 ('BURU SELATAN',31),
	 ('KEPULAUAN ARU',31),
	 ('TUAL',31),
	 ('HALMAHERA BARAT',32),
	 ('TIDORE KEPULAUAN',32),
	 ('TERNATE',32),
	 ('PULAU MOROTAI',32);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('KEPULAUAN SULA',32),
	 ('HALMAHERA SELATAN',32),
	 ('HALMAHERA TENGAH',32),
	 ('HALMAHERA TIMUR',32),
	 ('HALMAHERA UTARA',32),
	 ('YALIMO',33),
	 ('DOGIYAI',33),
	 ('ASMAT',33),
	 ('JAYAPURA',33),
	 ('PANIAI',33);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('MAPPI',33),
	 ('TOLIKARA',33),
	 ('PUNCAK JAYA',33),
	 ('PEGUNUNGAN BINTANG',33),
	 ('JAYAWIJAYA',33),
	 ('LANNY JAYA',33),
	 ('NDUGA',33),
	 ('BIAK NUMFOR',33),
	 ('KEPULAUAN YAPEN (YAPEN WAROPEN)',33),
	 ('PUNCAK',33);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('INTAN JAYA',33),
	 ('WAROPEN',33),
	 ('NABIRE',33),
	 ('MIMIKA',33),
	 ('BOVEN DIGOEL',33),
	 ('YAHUKIMO',33),
	 ('SARMI',33),
	 ('MERAUKE',33),
	 ('DEIYAI (DELIYAI)',33),
	 ('KEEROM',33);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('SUPIORI',33),
	 ('MAMBERAMO RAYA',33),
	 ('MAMBERAMO TENGAH',33),
	 ('RAJA AMPAT',34),
	 ('MANOKWARI SELATAN',34),
	 ('MANOKWARI',34),
	 ('KAIMANA',34),
	 ('MAYBRAT',34),
	 ('SORONG SELATAN',34),
	 ('FAKFAK',34);
INSERT INTO rsapp.kota (nama_kota,id_provinsi) VALUES
	 ('PEGUNUNGAN ARFAK',34),
	 ('TAMBRAUW',34),
	 ('SORONG',34),
	 ('TELUK WONDAMA',34),
	 ('TELUK BINTUNI',34);